CREATE TYPE "UserRole" AS ENUM ('SUPER_ADMIN', 'TEAM_MEMBER');

ALTER TABLE "User"
ADD COLUMN "role" "UserRole" NOT NULL DEFAULT 'SUPER_ADMIN';

ALTER TABLE "User"
ALTER COLUMN "role" SET DEFAULT 'TEAM_MEMBER';
